import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'antd/dist/antd.css';
import { Layout, Row, Col, Button, Avatar, Dropdown, Menu, Typography, Skeleton } from 'antd';
import { UserOutlined, MenuOutlined } from '@ant-design/icons';
import Image from 'next/image';
import { database } from '../firebase'
import { onValue, ref } from "firebase/database";
import MainHeader from '../components/Header';
import CardGallery from '../components/CardGallery';

const { Content } = Layout;

export const Parks = () => {
  const [items, setItems] = useState([])

  useEffect(() => {
    if (database) {
      let path = ref(database, 'parks');
      onValue(path, snapshot => {
        setItems(snapshot.val())
      });
    }
  }, [])
  return (
    <>
      <Head>
        <title>Dog Parks in Dallas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="layout">
        <MainHeader />
        <Content
          style={{
            background: '#ffffff'
          }}
        >
          <div className={styles.container}>
            <h1 className={styles.pageHeader}>Parks</h1>
            {/* <p>{items.length} parks within <Tag color="green">15 miles</Tag> of 75202</p> */}
            <CardGallery items={items} />
          </div>
          {/* <ShowMap /> */}
        </Content>
      </Layout>
    </>
  )
}


const ShowMap = () => {
  return (
    <div className={styles.showMap}>
      <Button className={styles.antBtn} type="primary">Show Map</Button>
    </div>
  )
}

export default Parks;